### ISSUE TITLE
Greenframe analyzes never ends

### ISSUE THREAD

**Issue by simonrenoult** [marmelab/greenframe-cli#58] opened 2023-08-04 00:44 UTC
Howdy 👋 

# Problem

Greenframe CLI analyzes never reaches an end.

# Reproduction steps

The following command remains pending and never produces a result.

```shell
$ cd ~
$ greenframe analyze https://marmelab.com 
✔ Check configuration file
✔ The folder is not a git repository
❯ Analysis is in progress locally
  ✔ Docker version 20.10.23, build 7155243
  ⠼ Running 1 scenario(s)... # this step never stops
```

# Information

```shell
➜  ~ node -v
v16.20.1
➜  ~ greenframe -v                          
greenframe-cli/1.6.8 darwin-arm64 node-v16.20.1
```

Am I missing something? Any idea what's going on?

**Comment by Nitix** [comment] 2023-08-07 07:45
Difficult to respond without reproduction.
But here some ideas of what can go wrong.
- Your website never finishes to load, for exemple a continuous music radio. Sometimes it can be ads, in this case you can use the `--useAdblock`. The default scenario wait for the network to be idle.
- Your website uses infinite scroll, the default scenario tries to scroll to the end, in this case you should provide your own scenario.

I'm closing the issue, since it's not really an issue.

**Closed by Nitix** 2023-08-07 07:45 UTC
